### ISSUE TITLE
Please invite me to the community

### ISSUE THREAD

**Issue by sijin-raj** [SurPathHub/support#50]
Invite me to the SurPath Hub Community.

- #### Name: Sijin Raj

- #### Country: India

- #### Discord Username(if exists): sijin#5147

- #### Additional Context:

> i saw in twitter and i search it and now there Discord Community

> i like to learn a new things and Help the beginner people one who have interest and interact and connect Community

**Comment by vinzvinci** [comment]
Looks like you don't follow our community guidelines: https://github.com/SurPathHub/support#guide

Thank you for your interest in joining our community. However, we are sad to say that this is a local community from the Philippines, and it will be hard for you to understand us due to the language barrier. Please join the [https://www.eddiehub.org/](EddieHub Community), instead. It is a global community where everyone can join. 

We are kicking you to this org.

Thank you for your understanding!

**Comment by sijin-raj** [comment]
Thank you for i have understanding!
